Copy review pt1
swapmyvote/swapmyvote pull request #592
Opened 2022-06-09 18:08 UTC by tdg

Copy review pt1 partly addresses #561

2022-06-09 18:12 UTC, tdg commented
Please could you review @joshr @baob @aspiers?
I'll continue with ptii asap

2022-06-09 18:38 UTC, aspiers commented on app/views/static_pages/faq.html.haml
> +    %a(name="parties")
I disagree with the hound dog on this one.

2022-06-09 18:40 UTC, aspiers commented on app/views/static_pages/faq.html.haml
> +    -
@tdg This doesn't look right.

2022-06-09 19:07 UTC, aspiers requested changes
Mostly looks great; see the few comments from hound and me.

2022-06-10 18:19 UTC, baob submitted a review, later dismissed

2022-06-11 01:17 UTC, aspiers commented
Rebased

2022-06-11 01:20 UTC, aspiers approved these changes

2022-06-11 01:20 UTC, merged